var gameArea = document.getElementById(`gameArea`), slideText = document.getElementById(`slideText`), slideResultText = document.getElementById(`slideResultText`), characterWordsBox = document.getElementById(`characterWordsBox`),
characters = document.getElementById(`characters`), continueButton = document.getElementById(`continueButton`), character = ``, rooms = ``, roomIndex = 0, room = rooms[roomIndex], srcIndex = 0, i = 0, speed = 35, sentences = `correctResponseSentences`, step = 0, failPoints = 0, winPoints = 0
continueButton.onclick = function() {updateCharacters(), makeSentence()}
function makeSentence() {if (room[sentences][step].sentence && i < room[sentences][step].sentence.length) {characterWordsBox.textContent += room[sentences][step].sentence[i], characterWordsBox.scrollTop = characterWordsBox.scrollHeight, i++, setTimeout(makeSentence, speed)} else {
    for (var j = 0; j < room[sentences][step].responses.length; j++) {
    if (room[sentences][step].responses[j].response) {var button = document.createElement(`button`)
    if (j == 0) characterWordsBox.appendChild(document.createElement(`br`))
    button.onclick = respond.bind(this, room[sentences][step].responses[j], true), button.style.color = `blue`, button.style.backgroundColor = `grey`, button.style.margin = `1.5%`, button.style.fontSize = `30px`, button.textContent = room[sentences][step].responses[j].response, characterWordsBox.appendChild(button)} characterWordsBox.scrollTop = characterWordsBox.scrollHeight
    if (!room[sentences][step].needButtonClick) return respond(room[sentences][step].responses[j])
}}}
function cleanGarage(response) {delete response.function, setTimeout(() => {gameArea.style.backgroundImage = `url(room3.jpg)`, setTimeout(() => {respond(response, true)}, 1000)}, 1000)}
function finishCookies(response) {delete response.function, character.style.top = `${parseFloat(getComputedStyle(character).top) + 80}px`, character.style.left = `${parseFloat(getComputedStyle(character).left) + 40}px`}
function respond(response, button) {if (button) {characterWordsBox.innerHTML = ``} if (Object.keys(response).some(key => document.getElementById(key) && typeof response[key] == `boolean`)) Object.keys(response).filter(key => document.getElementById(key) && typeof response[key] == `boolean`).forEach(key => {document.getElementById(key).hidden = !response[key]})
if (response.function) return window[response.function](response)
if (response.responseSrcIndex != undefined) srcIndex = response.responseSrcIndex, updateCharacters()
if (response.end && characterWordsBox.innerHTML == ``) {setTimeout(() => {slideResultText.style.fontSize = response.size, slideResultText.style.color = response.color, slideResultText.textContent = response.end, slideResultText.hidden = false; if (response.nextRoom) {roomIndex++} if (slideResultText.style.color == `green`) {winPoints++} else {failPoints++}}, 1000)
return setTimeout(() => {if (Object.values(response).some(val => val === false || val == `remove`)) {Object.keys(response).filter(key => response[key] == false || response[key] == `remove`).forEach(key => document.getElementById(key).remove())}
gameArea.style.backgroundImage = ``; characterWordsBox.hidden = true, slideResultText.hidden = true, Array.from(gameArea.children).filter(elem => elem.id[0].toUpperCase() == elem.id[0]).forEach(character => character.hidden = true), slideText.hidden = false; if (response.nextRoom) {continueButton.hidden = false} step = 0, srcIndex = 0, sentences = `correctResponseSentences`
if (response.nextRoom) {slideText.textContent = `Day ${roomIndex + 1}`} else {slideText.style.marginBottom = `125px`; if (winPoints >= rooms.length / 2) {return slideText.textContent = `You are responsible! Keep being responsible because it helps you be a better person, and you don't always know what the consequences are.`} else return slideText.textContent = `You are not very responsible. You need to be more responsible because it helps you be a better person, and you don't always know what the consequences are.`} return}, response.endWaitTime)}
if (response.type == `correct`) sentences = `correctResponseSentences`, step = response.responseSentenceIndex
if (response.type == `wrong`) sentences = `wrongResponseSentences`, step = response.responseSentenceIndex
if (characterWordsBox.innerHTML == ``) {i = 0; if (room[sentences][step].pause) {return setTimeout(makeSentence, room[sentences][step].pause)} makeSentence()}}
function selectCharacter(element) {character = element, character.onclick = ``, Array.from(gameArea.children).find(elem => elem.id == `chooseCharacter`).remove(), characters.hidden = true, continueButton.hidden = false, slideText.textContent = `Day ${roomIndex + 1}`, slideText.hidden = false,
rooms = [{srcs: [{src: `room1.jpg`, characters: [{character: character.id, left: `40%`, top: `45%`}, {character: character.style.getPropertyValue(`--parentName`), left: `80%`, top: `35%`}]}, {src: `room2.jpg`, characters: [{character: character.id, left: `50%`, top: `30%`}]}], correctResponseSentences: [{sentence: `You are watching TV.`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 1}]},
{sentence: `Your ${character.style.getPropertyValue(`--parent`)} walks in.`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 2, [character.style.getPropertyValue(`--parentName`)]: true}]},
{sentence: `${character.style.getPropertyValue(`--parentPronoun`)[0].toUpperCase() + character.style.getPropertyValue(`--parentPronoun`).slice(1)} says, "You need to clean the garage. We are bringing home a new car in 5 hours."`, needButtonClick: true, responses: [{response: `Ok, I will.`, type: `correct`, responseSentenceIndex: 3, [character.style.getPropertyValue(`--parentName`)]: false}, {response: `No`, type: `wrong`, responseSentenceIndex: 0}]},
{sentence: `Now or later?`, needButtonClick: true, responses: [{response: `Now`, type: `correct`, responseSentenceIndex: 4, responseSrcIndex: 1}, {response: `Later`, type: `correct`, responseSentenceIndex: 6}]}, {responses: [{function: `cleanGarage`, type: `correct`, responseSentenceIndex: 8, responseSrcIndex: 0}]}, { responses: [{function: `cleanGarage`, type: `correct`, responseSentenceIndex: 7, responseSrcIndex: 0}]},
{sentence: `It's now 3 hours later. Do you start cleaning the garage?`, needButtonClick: true, responses: [{response: `Yes`, type: `correct`, responseSentenceIndex: 5, responseSrcIndex: 1}, {response: `No`, type: `wrong`, responseSentenceIndex: 2}]}, {pause: 1000, sentence: `2 hours later, the car gets here.`, responses: [{response: `Continue`, [character.style.getPropertyValue(`--parentName`)]: true, end: `Great job! You were responsible.`, color: `green`, size: `110px`, nextRoom: true, endWaitTime: 3000}]},
{pause: 1000, sentence: `5 hours later, the car gets here.`, responses: [{response: `Continue`, [character.style.getPropertyValue(`--parentName`)]: true, end: `Great job! You were responsible.`, color: `green`, size: `110px`, nextRoom: true, endWaitTime: 3000}]}],
wrongResponseSentences: [{sentence: `${character.style.getPropertyValue(`--parentPronoun`)[0].toUpperCase() + character.style.getPropertyValue(`--parentPronoun`).slice(1)} says, "${character.id}, the garage better be cleaned by the time the car gets here.`, needButtonClick: true, responses: [{response: `Ok`, type: `correct`, responseSentenceIndex: 6, [character.style.getPropertyValue(`--parentName`)]: false}, {response: `That's not fair!`, type: `wrong`, responseSentenceIndex: 1}]},
{sentence: `${character.style.getPropertyValue(`--parentPronoun`)[0].toUpperCase() + character.style.getPropertyValue(`--parentPronoun`).slice(1)} says, "Maybe you should try to be responsible."`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 6, [character.style.getPropertyValue(`--parentName`)]: false}]}, {pause: 1000, sentence: `2 hours later, the car gets here.`, responses: [{response: `Continue`, [character.style.getPropertyValue(`--parentName`)]: true, end: `You lose technology for a day. You weren't responsible.`, color: `darkred`, size: `90px`, nextRoom: true, endWaitTime: 4000}]}]},
{srcs: [{src: `room4.jpg`, characters: [{character: character.id, left: `10%`, top: `40%`}, {character: character.style.getPropertyValue(`--parentName`), left: `60%`, top: `45%`}]}, {src: `room5.jpg`, characters: [{character: character.id, left: `50%`, top: `30%`}, {character: character.style.getPropertyValue(`--friend`), left: `20%`, top: `30%`}]},
{src: `room5.jpg`, characters: [{character: character.id, left: `50%`, top: `30%`}, {character: character.style.getPropertyValue(`--friend`), left: `20%`, top: `30%`}]}], correctResponseSentences: [{sentence: `You are about to make cereal.`, needButtonClick: true, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 1}]}, {sentence: `You accidentally trip and spill lots of milk.`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 2, [`milk`]: true}]},
{sentence: `Are you going to clean it up?`, needButtonClick: true, responses: [{response: `Yes`, type: `correct`, responseSentenceIndex: 3}, {response: `No`, type: `wrong`, responseSentenceIndex: 2, responseSrcIndex: 1, [`milk`]: false}]}, {sentence: `Now or later?`, needButtonClick: true, responses: [{response: `Now`, type: `correct`, responseSentenceIndex: 4}, {response: `Later`, type: `wrong`, responseSentenceIndex: 0, responseSrcIndex: 1, [`milk`]: false}]},
{pause: 1000, responses: [{[`milk`]: false, end: `Great job! You were responsible.`, color: `green`, size: `110px`, nextRoom: true, endWaitTime: 3000}]}], wrongResponseSentences: [{pause: 1000, sentence: `It's now 2 hours later. You are at the park with your friend. Are you going to clean up the milk now?`, needButtonClick: true, responses: [{response: `Yes`, type: `wrong`, responseSentenceIndex: 1}, {response: `No`, type: `wrong`, responseSentenceIndex: 2}]},
{pause: 1000, sentence: `You come into the kitchen to clean up the milk.`, responses: [{response: `Continue`, type: `wrong`, responseSentenceIndex: 3, responseSrcIndex: 0, [`milk`]: true}]}, {pause: 1000, sentence: `2 hours later, you come into the kitchen for a snack after hanging out at the park with your friend.`, responses: [{response: `Continue`, type: `wrong`, responseSentenceIndex: 3, responseSrcIndex: 0, [`milk`]: true}]},
{sentence: `There are milk stains on the floor because the milk was out for too long.`, needButtonClick: true, responses: [{response: `Continue`, [character.style.getPropertyValue(`--parentName`)]: true, [`milk`]: `remove`, end: `You are grounded for a week. You weren't responsible.`, color: `darkred`, size: `90px`, nextRoom: true, endWaitTime: 4000}]}]}, {srcs: [{src: `room4.jpg`, characters: [{character: character.id, left: `20%`, top: `30%`}]}, {src: `room6.jpg`, characters: [{character: character.id, left: `50%`, top: `30%`}]}, {src: `room1.jpg`, characters: [{character: character.id, left: `40%`, top: `45%`}]}],
correctResponseSentences: [{sentence: `You are making cookies.`, needButtonClick: true, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 1}]}, {sentence: `You look at the time and realize it's 8:00 at night. You have a lot of homework, and you haven't done it.`, needButtonClick: true, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 2}]}, {pause: 1000, sentence: `You finish making the cookies.`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 3, [`cookies`]: true, function: `finishCookies`}]},
{sentence: `Do you start on your homework?`, needButtonClick: true, responses: [{response: `Yes`, [`cookies`]: false, responseSrcIndex: 1, end: `Great job! You were responsible.`, color: `green`, size: `110px`, endWaitTime: 3000}, {response: `No`, type: `wrong`, responseSentenceIndex: 0, responseSrcIndex: 2, [`cookies`]: false}]}], wrongResponseSentences: [{pause: 1000, sentence: `You finish watching a movie and realize the time is 10:00 at night.`, needButtonClick: true, responses: [{response: `Continue`, [`cookies`]: `remove`, end: `You weren't responsible.`, color: `darkred`, size: `110px`, nextRoom: true, endWaitTime: 2000}]}]},
{srcs: [{src: `room7.jpg`, characters: [{character: character.id, left: `45%`, top: `50%`}, {character: character.style.getPropertyValue(`--teacher`), left: `55%`, top: `3%`, hidden: false}, {character: character.style.getPropertyValue(`--cousin1`), left: `5%`, top: `15%`}, {character: character.style.getPropertyValue(`--cousin2`), left: `85%`, top: `25%`}, {character: character.style.getPropertyValue(`--friend`), left: `45%`, top: `15%`}]},
{src: `room8.jpg`, characters: [{character: character.id, left: `40%`, top: `40%`}]}, {src: `room9.jpg`, characters: [{character: character.id, left: `50%`, top: `20%`}]}, {src: `room4.jpg`, characters: [{character: character.id, left: `30%`, top: `45%`}, {character: character.style.getPropertyValue(`--parentName`), left: `60%`, top: `45%`}]}],
correctResponseSentences: [{sentence: `You are in school. Your class is about to go over the homework assignment from yesterday.`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 1}]}, {sentence: `When your teacher realizes you didn't finish your homework, she gives you an hour long detention after school so you can finish your homework.`, responses: [{response: `Continue`, type: `correct`, responseSentenceIndex: 2, responseSrcIndex: 1}]},
{pause: 1000, sentence: `School is over, and no teacher has gotten you in the detention room. Do you start to go home?`, needButtonClick: true, responses: [{response: `Yes`, type: `wrong`, responseSentenceIndex: 0, responseSrcIndex: 2}, {response: `No`, responseSrcIndex: 0, end: `Great job! You were responsible.`, color: `green`, size: `110px`, endWaitTime: 3000}]}],
wrongResponseSentences: [{pause: 1000, sentence: `You get home.`, responses: [{responseSrcIndex: 3, response: `Continue`, [character.style.getPropertyValue(`--parentName`)]: true, end: `Since your ${character.style.getPropertyValue(`--parent`)} knew about your detention, you lose technology for a week. You weren't responsible.`, color: `darkred`, size: `70px`, endWaitTime: 6000}]}]}]}
function updateCharacters() {room = rooms[roomIndex], i = 0, slideText.hidden = true, continueButton.hidden = true, gameArea.style.backgroundImage = `url(${room.srcs[srcIndex].src})`
room.srcs[srcIndex].characters.forEach(character => {if (typeof character.character == `string`) {character.character = Array.from(characters.children).concat(Array.from(gameArea.children)).find(elem => elem.id == character.character)} if (Array.from(gameArea.children).filter(elem => elem.id && elem.id[0].toUpperCase() == elem.id[0]).some(elem => !room.srcs[srcIndex].characters.some(character => character.character == elem))) Array.from(gameArea.children).filter(elem => elem.id && elem.id[0].toUpperCase() == elem.id[0]).filter(elem => !room.srcs[srcIndex].characters.some(character => character.character == elem)).forEach(elem => elem.hidden = true)})
characterWordsBox.style.top = `${parseFloat(gameArea.style.height) - parseFloat(characterWordsBox.style.height) - 0.015 * parseFloat(gameArea.style.height) * 2}px`, characterWordsBox.hidden = false, room.srcs[srcIndex].characters.forEach(character => {character.character.style.position = `absolute`, character.character.width = 90, character.character.height = 190, character.character.style.left = character.left, character.character.style.top = character.top; if (character.hidden != undefined) {character.character.hidden = character.hidden} gameArea.appendChild(character.character)}), character.hidden = false}